# -------------------------------
# CityPulse Project Secret Config
# -------------------------------

# OpenAQ API Key (for real air quality data)
OPENAQ_API_KEY=your_openaq_api_key_here

# Twitter API keys (for sentiment analysis)
TWITTER_API_KEY=your_twitter_api_key
TWITTER_API_SECRET=your_twitter_api_secret
TWITTER_ACCESS_TOKEN=your_twitter_access_token
TWITTER_ACCESS_SECRET=your_twitter_access_secret

# Google Maps API (for geolocation or traffic data)
GOOGLE_MAPS_API_KEY=your_google_maps_api_key

# Database (if using PostgreSQL, MongoDB etc.)
DB_URI=your_db_connection_string_here

# Secret key for Streamlit session or other services
APP_SECRET_KEY=super_secret_key_here
